config/routes.rb
Rails.application.routes.draw do

 
	devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",
																			:registrations => "registrations", :invitations => 'invitations'}

	match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

	get '/users/invitation/invite' => 'users#invite'
	get '/users/fbshare' => 'users#fbshare'
	get '/users/fbshare_accept' => 'users#fbshare_accept'
	root 'home#index'

	post 'home/search' => 'home#search'
	post 'set_currency' => 'application#set_currency'

	post '/home_products' => 'home#home_products'

	post 'twilio/voice' => 'twilio#voice'
	post 'notifications/notify' => 'notifications#notify'
	post 'twilio/status' => 'twilio#status'
	
	resources :products do
		member do
			match "edit_basic",  via: [:get]
			match "edit_description",  via: [:get]
			match "edit_location",  via: [:get]
			match "edit_photo",  via: [:get]
			match "edit_price",  via: [:get]
			post "write_comment" => 'products#write_comment'
			post "remove_comment" => 'products#remove_comment'
			match "set_status", via: [:post]
		end
	end

	resources :cities do
		member do
			match "category", via: [:get]
		end
	end

	resource :place do
		

		get ':slug' => 'places#search_place'
		post ':slug' => 'places#search_place'
	end
	
	resources :store
	resources :product_attachments
	resources :store_images
	resources :user_avatars
	resources :profile_documents
	resources :account_documents

	post 'invoices/new' => 'invoices#new'
	get 'invoices/success_checkout' => "invoices/success_checkout"
	get 'invoices/cancel_checkout' => "invoices/cancel_checkout"

	get 'invoices/checkout/:slug' => 'invoices#display', :as => 'slug_invoice'
	resources :invoices do
		member do
			match 'abandoned_checkout', via: [:get]
		end
	end
	resource :invoices do

	end

	get 'become_merchant' => 'users#become_merchant'
	post 'become_merchant' => 'users#become_merchant'
	get 'merchant' => 'users#merchant_landing'
	get 'profile' => 'users#profile'
	post 'profile' => 'users#profile'
	patch 'profile' => 'users#profile'
	get 'profile/avatar' => 'users#profile_avatar'
	post 'profile/avatar' => 'users#profile_avatar'
	patch 'profile/avatar' => 'users#profile_avatar'
	get 'profile/security' => 'users#profile_security'
	post 'profile/security' => 'users#profile_security'
	patch 'profile/security' => 'users#profile_security'

	resource :user do
		match 'account_document', via: [:get, :post, :patch]
		match 'getting_paid', via: [:get, :post, :patch]
	end

	get 'accounts' => 'users#accounts'
	post 'accounts' => 'users#accounts'
	patch 'accounts' => 'users#accounts'
	get 'accounts/photo' => 'users#accounts_photo'
	post 'accounts/photo' => 'users#accounts_photo'
	patch 'accounts/photo' => 'users#accounts_photo'

	get 'profile/photos' => 'users#photos'
	post 'profile/photos' => 'users#photos'
	post 'complete_merchant' => 'users#complete_merchant'
	get 'verify_document' => 'users#verify_merchant'
	get 'dashboard' => 'users#dashboard'

	get 'about' => 'users#about'
	get 'blog' => 'users#blog'
	get 'career' => 'users#career'
	get 'contact' => 'users#contact'
	get 'press' => 'users#press'
	get 'terms' => 'users#terms'
	get 'policy' => 'users#policy'
	get 'help' => 'users#help'

	get 'users/verify_store_username' => 'users#verify_store_username'

	resources :trips do
		post 'update_status' => 'trips#update_status'
	end

	resource :trips do
		get 'checkout/:slug' => 'trips#display', :as => 'slug_trip_checkout'
	end

	resources :reservations do
		post 'update_status' => 'reservations#update_status'
		
	end
	resource :reservations do
		get 'checkout/:slug' => 'reservations#display', :as => 'slug_reservation_checkout'
	end

	get 'reservations/show/:slug' => 'reservations#display', :as => 'slug_reservation'

	resource :coupons do
		match 'get_coupon', via: [:get, :post]
	end

	resource :comments do
		match 'create_comment', via: [:post]
		match 'remove_comment', via: [:post]
		match 'update_comment', via: [:post]
	end
	

	namespace :api, defaults: {format: 'json'}  do
		namespace :v1 do
			resource :users do
				match 'login', via: [:post]
				match 'signup', via: [:post]
			end
			get 'profile' => 'users#profile'
		end
	end

end

app/views/shared/_accounts_nav.html.erb
<div class="col-xs-12 col-sm-3 col-md-3 sidebar-profile-dashboard">
	<ul class="sidebar-static">
	  <li><%= link_to 'Edit Accounts', accounts_path %></li>
	  <li><%= link_to 'Getting Paid', getting_paid_user_path %></li>
	  <li><%= link_to 'Upload Store Logo', accounts_photo_path %></li>
	  <li><%= link_to 'Store Verification', account_document_user_path %></li>
	</ul>
	<!-- <a href="" class="btn btn-viewprofile">View Accounts</a> -->
</div>

app/views/shared/_errors.html.erb
<% if obj.present? && obj.errors.any? %>
	<div>
		<% obj.errors.full_messages.each do |msg| %>
			<label class="error">
				<%= msg %>
			</label>
		<% end %>
	</div>
<% end %>

app/views/shared/_flash.html.erb
<!-- <div class="container"> -->
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>" id="flash"><%= value %></div>
	<% end %>
<!-- </div> -->

app/views/shared/_listing_left_nav.html.erb
<ul class="sidebar-static">
	<li class="<%= 'active' if obj == 'listings' %>"><a href="/products">Your Listings</a></li>
	<li class="<%= 'active' if obj == 'reservations' %>"><a href="/reservations">Your Reservations</a></li>

	<!-- <li class="<%= 'active' if obj == 'requirements' %>"><a href="">Reservation Requirements</a></li> -->
</ul>
<a href="/products/new" class="btn btn-block btn-viewprofile">Add New Listings</a>

app/views/shared/_profile_nav.html.erb
<div class="col-xs-12 col-sm-3 col-md-3 sidebar-profile-dashboard">
	<ul class="sidebar-static">
	  <li class="<%= 'active' if obj == 'profile' %>"><%= link_to 'Edit Profile', profile_path %></li>
	  <li class="<%= 'active' if obj == 'photo' %>"><%= link_to 'Upload Profile Photo', profile_avatar_path %></li>

	  <!-- <li class="<%= 'active' if obj == 'document' %>"><a href="/user/profile_document">Trust and Verification</a></li> -->

	  <li class="<%= 'active' if obj == 'photo' %>"><%= link_to 'Security', profile_security_path %></li>
	  <!-- <li class="<%= 'active' if obj == 'review' %>"><a href="">Reviews</a></li>
	  <li class="<%= 'active' if obj == 'reference' %>"><a href="">References</a></li> -->
	</ul>
	<!-- <a href="" class="btn btn-viewprofile">View Profile</a> -->
</div>

<style>
/*	.profile-form input {
    background-color: #FFF;
    border: 1px solid #adadad;
    color: black;
	}*/
</style>

app/views/shared/_settings_nav.html.erb
<nav class="navbar navbar-static-top nav-second-profile">
	<div class="container">
		<div id="" class="">
			<ul class="nav navbar-nav">
				<li class="<%= 'active' if obj == 'dashboard' %>"><a href="/dashboard">Dashboard</a></li>
				<% if current_user.status == 'merchant' %>
				<li class="<%= 'active' if obj == 'listing' %>"><a href="/products">Listing</a></li>
				<% end %>
				<li class="<%= 'active' if obj == 'trips' %>"><a href="/trips">Trips</a></li>
				<li class="<%= 'active' if obj == 'profile' %>"><%= link_to 'Profile', profile_path %></li>
				<% if current_user.status == 'merchant' %>
					<li class="<%= 'active' if obj == 'accounts' %>"><%= link_to 'Store', accounts_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/shared/_static_nav.html.erb
<nav class="navbar navbar-static-top nav-second-profile subnav-dark">
	<div class="container">
		<div id="" class="">
			<ul class="nav navbar-nav ">
				<li class="<%= 'active' if obj == 'about' %>"><a href="/about">About Us</a></li>
				<li class="<%= 'active' if obj == 'press' %>"><a href="/press">Press</a></li>
				<!-- <li class="<%= 'active' if obj == 'career' %>"><a href="/career">Career</a></li> -->
				<!-- <li class="<%= 'active' if obj == 'blog' %>"><a href="/blog">Blog</a></li> -->
				<li class="<%= 'active' if obj == 'contact' %>"><a href="/contact">Contact</a></li>
				<li class="<%= 'active' if obj == 'policy' %>"><a href="/policy">Policy</a></li>
				<!-- <li class="<%= 'active' if obj == 'help' %>"><a href="/help">Help</a></li> -->
				<li class="<%= 'active' if obj == 'terms' %>"><a href="/terms">Terms</a></li>
			</ul>
		</div>
		<!--/.nav-collapse -->
	</div>
</nav>

app/views/shared/_store_setting_errors.html.erb
<% if obj.present? && obj.errors.any? %>
	<div>
		<% obj.errors.full_messages.each do |msg| %>
			<label class="error">
				<%= msg %>
			</label>
		<% end %>
	</div>
<% end %>