config/routes.rb
Rails.application.routes.draw do

 
	devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",
																			:registrations => "registrations", :invitations => 'invitations'}

	match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

	get '/users/invitation/invite' => 'users#invite'
	get '/users/fbshare' => 'users#fbshare'
	get '/users/fbshare_accept' => 'users#fbshare_accept'
	root 'home#index'

	post 'home/search' => 'home#search'
	post 'set_currency' => 'application#set_currency'

	post '/home_products' => 'home#home_products'

	post 'twilio/voice' => 'twilio#voice'
	post 'notifications/notify' => 'notifications#notify'
	post 'twilio/status' => 'twilio#status'
	
	resources :products do
		member do
			match "edit_basic",  via: [:get]
			match "edit_description",  via: [:get]
			match "edit_location",  via: [:get]
			match "edit_photo",  via: [:get]
			match "edit_price",  via: [:get]
			post "write_comment" => 'products#write_comment'
			post "remove_comment" => 'products#remove_comment'
			match "set_status", via: [:post]
		end
	end

	resources :cities do
		member do
			match "category", via: [:get]
		end
	end

	resource :place do
		

		get ':slug' => 'places#search_place'
		post ':slug' => 'places#search_place'
	end
	
	resources :store
	resources :product_attachments
	resources :store_images
	resources :user_avatars
	resources :profile_documents
	resources :account_documents

	post 'invoices/new' => 'invoices#new'
	get 'invoices/success_checkout' => "invoices/success_checkout"
	get 'invoices/cancel_checkout' => "invoices/cancel_checkout"

	get 'invoices/checkout/:slug' => 'invoices#display', :as => 'slug_invoice'
	resources :invoices do
		member do
			match 'abandoned_checkout', via: [:get]
		end
	end
	resource :invoices do

	end

	get 'become_merchant' => 'users#become_merchant'
	post 'become_merchant' => 'users#become_merchant'
	get 'merchant' => 'users#merchant_landing'
	get 'profile' => 'users#profile'
	post 'profile' => 'users#profile'
	patch 'profile' => 'users#profile'
	get 'profile/avatar' => 'users#profile_avatar'
	post 'profile/avatar' => 'users#profile_avatar'
	patch 'profile/avatar' => 'users#profile_avatar'
	get 'profile/security' => 'users#profile_security'
	post 'profile/security' => 'users#profile_security'
	patch 'profile/security' => 'users#profile_security'

	resource :user do
		match 'account_document', via: [:get, :post, :patch]
		match 'getting_paid', via: [:get, :post, :patch]
	end

	get 'accounts' => 'users#accounts'
	post 'accounts' => 'users#accounts'
	patch 'accounts' => 'users#accounts'
	get 'accounts/photo' => 'users#accounts_photo'
	post 'accounts/photo' => 'users#accounts_photo'
	patch 'accounts/photo' => 'users#accounts_photo'

	get 'profile/photos' => 'users#photos'
	post 'profile/photos' => 'users#photos'
	post 'complete_merchant' => 'users#complete_merchant'
	get 'verify_document' => 'users#verify_merchant'
	get 'dashboard' => 'users#dashboard'

	get 'about' => 'users#about'
	get 'blog' => 'users#blog'
	get 'career' => 'users#career'
	get 'contact' => 'users#contact'
	get 'press' => 'users#press'
	get 'terms' => 'users#terms'
	get 'policy' => 'users#policy'
	get 'help' => 'users#help'

	get 'users/verify_store_username' => 'users#verify_store_username'

	resources :trips do
		post 'update_status' => 'trips#update_status'
	end

	resource :trips do
		get 'checkout/:slug' => 'trips#display', :as => 'slug_trip_checkout'
	end

	resources :reservations do
		post 'update_status' => 'reservations#update_status'
		
	end
	resource :reservations do
		get 'checkout/:slug' => 'reservations#display', :as => 'slug_reservation_checkout'
	end

	get 'reservations/show/:slug' => 'reservations#display', :as => 'slug_reservation'

	resource :coupons do
		match 'get_coupon', via: [:get, :post]
	end

	resource :comments do
		match 'create_comment', via: [:post]
		match 'remove_comment', via: [:post]
		match 'update_comment', via: [:post]
	end
	

	namespace :api, defaults: {format: 'json'}  do
		namespace :v1 do
			resource :users do
				match 'login', via: [:post]
				match 'signup', via: [:post]
			end
			get 'profile' => 'users#profile'
		end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	skip_before_action :authenticate_user!, only: [:index, :home_products]

	def index

		# @products = Product.random_active.limit(6).includes(:product_attachments).includes(:product_reviews)
		@products = Product.public_active.order('random()').limit(6).includes(:product_attachments).includes(:product_reviews)

		@products.each do |product|
			if product.currency != session[:currency]
				if session["currency-convert-#{product.currency}"].to_f == 0.0
					rate = 1.0	
				else
					rate = session["currency-convert-#{session[:currency]}"].to_f / session["currency-convert-#{product.currency}"].to_f
				end
	      
	    else
	      rate = 1.0
	    end

			product.price_with_currency = (product.price_cents * rate / 100).round(2)
			product.current_currency = session[:currency]
		end
		@product_attachments = ProductAttachment.all 
		#logger.info "status=Fetching Home Product image=#{@products.product_attachments.try(:first).attachment}" 

		@countries = Product.select(:country).distinct.where("country is not null and country <> ''").pluck(:country)
		@cities = Product.select(:city).distinct.where("city is not null and city <> ''").pluck(:city)
		
		# process for case insentive
		# @countries.each do |country|
		# 	country = country.split.map(&:capitalize).join(' ')
		# end

		@countries.map! {|country| country.split.map(&:capitalize).join(' ')}

		# @cities.each do |city|
		# 	city = city.split.map(&:capitalize).join(' ')
		# end

		@cities.map! {|city| city.split.map(&:capitalize).join(' ')}

		@countries = @countries.uniq
		@cities = @cities.uniq


		gon.search_location_list = @countries + @cities
		gon.search_interests = ProductCategory.select(:name).pluck(:name)
		@search_location_list = @countries + @cities
		# gon.home_products = @products

		# count per city
		@count_per_city = {}
		@cities.each do |city|
			@count_per_city[city] = Product.public_active.where("lower(city) LIKE ? or lower(country) like ?", "%#{city.downcase}%", "%#{city.downcase}%").count
		end

		@products.each do |product|
			product.set_extra_attributes
		end

	end

	def home_products
		city = params[:city]
		if city.downcase == 'all cities'
			@products = Product.public_active.order('random()').limit(6).includes(:product_attachments).includes(:product_reviews)
		else
			@products = Product.public_active.order('random()').where("lower(city) LIKE ? or lower(country) like ?", "%#{params[:city].downcase}%", "%#{params[:city].downcase}%").limit(6)
		end
		
		@products.each do |product|
			if product.currency != session[:currency]
	      rate = session["currency-convert-#{session[:currency]}"].to_f / session["currency-convert-#{product.currency}"].to_f
	    else
	      rate = 1.0
	    end

			product.price_with_currency = (product.price_cents * rate / 100).round(2)
			product.current_currency = session[:currency]
		end

		@products.each do |product|
			product.set_extra_attributes
		end
		render :layout => false
	end

	# def search
	# 	render :template => "products/result"
	# end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_product_section.html.erb
<section class="content-7 landing-trending">
	<div>
		<div class="container">
			<h3>
				Things to Do This Week in
				<div class="dropdown trending-list">
					<a href="" data-toggle="dropdown" class="select-trending">All Cities <span class="caret"></span></a>
					<input type="hidden" value="all cities" class="location">
					<ul class="dropdown-menu" aria-labelledby="" id="trending-location">
						<li><a href="">All Cities</a></li>
						<!-- <li><a href="">Kuala Lumpur</a></li>
						<li><a href="">Johor</a></li>
						<li><a href="">Kedah</a></li>
						<li><a href="">Kelantan</a></li>
						<li><a href="">Melaka</a></li>
						<li><a href="">Negeri Sembilan</a></li>
						<li><a href="">Pahang</a></li>
						<li><a href="">Perak</a></li>
						<li><a href="">Perlis</a></li>
						<li><a href="">Pulau Pinang</a></li>
						<li><a href="">Sabah</a></li>
						<li><a href="">Sarawak</a></li>
						<li><a href="">Selangor</a></li>
						<li><a href="">Terengganu</a></li>
						<li><a href="">Labuan</a></li> -->
						<% @cities.each do |city| %>
							<% if @count_per_city[city] >= 6 %>
								<li><a href=""><%= city %></a></li>
							<% end %>
						<% end %>
					</ul>
				</div>
			</h3>
			<p class="oneliner">Discover amazing outdoor adventures, activities, and tours</p>

			<div id="product-list">
				<div class="row">
					<% @products.each do |product| %>
						<div class="col-sm-6 col-md-4 col-lg-4 product-card">
						<% if product.product_discount != 1 %>
							<p class="price pull-right text-right">
							<span class="discount">

							from <strike><em><%= get_all_currency_symbols[product.current_currency] %></em> <%= product.price_with_currency %></strike>
							</span>
							<br>
							<em><%= get_all_currency_symbols[product.current_currency] %></em> <%= (product.price_with_currency.to_d * product.product_discount).round(2) %></p>
						<% else %>
							<p class="price"><%= get_all_currency_symbols[product.current_currency] %> <%= product.price_with_currency %></p>
						<% end %>
							


							
							<a href="<%= product_path product %>"><img src="<%= product.store_logo_url %>" class="img-circle user-thumb" width="52" alt="<%=product.user.store_setting.store_name %>"/></a>

							<p class="star-rating" style="position: absolute;">
								
								<i class="fa fa-star <%= 'empty-star' if product.review_mark <= 0 %>"></i>
								<i class="fa fa-star <%= 'empty-star' if product.review_mark <= 1 %>"></i>
								<i class="fa fa-star <%= 'empty-star' if product.review_mark <= 2 %>"></i>
								<i class="fa fa-star <%= 'empty-star' if product.review_mark <= 3 %>"></i>
								<i class="fa fa-star <%= 'empty-star' if product.review_mark <= 4 %>"></i>
								
							</p>


							<div class="img-holder">
								<a href="<%= product_path product %>">
									<img src="<%= product.product_attachments.first.attachment.square.url if product.product_attachments.first.present? %>" alt="<%= product.name %>" style="width: 100%;">
								</a>
							</div>
							<h4>
								<a href="<%= product_path product %>"><%=h truncate(product.name, :length => 30) %></a>
							</h4>
							<a href="<%= product_path product %>">
								<p><%= product.city%>, <%= product.country%></p>
							</a>

						</div>
					<% end %>
				</div>
			</div>
			<div class="row">
				<form method="POST" action="/place/all" id="trending-form">
					<%= tag(:input, :name => 'authenticity_token', :type => "hidden", :value => form_authenticity_token) %>
					<% ProductCategory.order('id').each do |category| %>
						<input type="hidden" name="category_<%= category.id %>" value="1">
					<% end %>
					<input type="hidden" name="city" value="all cities">
					<div class="col-sm-6 col-md-4 col-lg-4 col-xs-offset-4 all-destinations-sections">
						<button type="submit" class="btn btn-block btn-destination">See All Destinations</button>
						<!-- <a href="#" class="btn btn-block btn-destination">See All Destinations</a> -->
					</div>
				</form>
			</div>
			
		</div>
	</div>
</section>

<script>
	$(document).ready(function() { 
  	// initResponsiveHeader(); 
  	$('#trending-location li a').on('click', function(event) {
  		event.preventDefault();
  		
  		var location = $(this).text();
  		mixpanel.track("Trending city",{location});
  		var formData = new FormData();
  		formData.append('city', location);
  		$.ajax({
			  url: '/home_products',
			  // dataType: "json",
			  data: formData,
			  cache: false,
			  contentType: false,
			  processData: false,
			  type: 'POST',
			  success: function(data) {
			  	console.log('success');
			  	$('.select-trending').empty();
			  	$('.select-trending').append(location + ' ' + '<span class="caret"></span>');
			  	$('#trending-form input[name=city]').val(location);
			  	$('#product-list').empty();
			  	$('#product-list').append(data);
			  	console.log(location);
			  	if (location != 'All Cities') {
			  		var search_url = '/place/' + location.toLowerCase().replace(new RegExp(' ', 'g'), '-');
			  		// $('a.btn-destination').attr('href', '/place/' + location.toLowerCase().replace(new RegExp(' ', 'g'), '-'));
			  		$('#trending-form').attr('action', search_url);
			  	};
			  },
			  error: function(error) {
	      	console.log(error);
	      },
	      timeout: 10000
			});
  	})

  	$('#trending-form button').on('click', function() {
  		// $('#trending-form').find('[name="city"]').val('all cities');
  	})

  	

  });

</script>

<style>
	p.star-rating {
		position: absolute;
    top: 390px;
    right: 24px;
	}

	.glyphicon-star {
    color: #ffcd00;
	}

	.glyphicon-star.empty-star {
		color: #d8d8d8;
	}

	.star-rating i.empty-star {
		color: #d8d8d8;	
	}

	.star-rating i {
		color: #ffcd00;
	}
</style>

app/views/home/_product_section_backup.html.erb
<section class="content-7 landing-trending">
	<div>
		<div class="container">
			<h3>
				Now trending in 
				<div class="dropdown trending-list">
					<a href="" data-toggle="dropdown" class="select-trending">All Cities <span class="caret"></span></a>
					<input type="hidden" value="all cities" class="location">
					<ul class="dropdown-menu" aria-labelledby="" id="trending-location">
						<li><a href="">All Cities</a></li>
						<!-- <li><a href="">Kuala Lumpur</a></li>
						<li><a href="">Johor</a></li>
						<li><a href="">Kedah</a></li>
						<li><a href="">Kelantan</a></li>
						<li><a href="">Melaka</a></li>
						<li><a href="">Negeri Sembilan</a></li>
						<li><a href="">Pahang</a></li>
						<li><a href="">Perak</a></li>
						<li><a href="">Perlis</a></li>
						<li><a href="">Pulau Pinang</a></li>
						<li><a href="">Sabah</a></li>
						<li><a href="">Sarawak</a></li>
						<li><a href="">Selangor</a></li>
						<li><a href="">Terengganu</a></li>
						<li><a href="">Labuan</a></li> -->
						<% @cities.each do |city| %>
							<% if @count_per_city[city] >= 6 %>
								<li><a href=""><%= city %></a></li>
							<% end %>
						<% end %>
					</ul>
				</div>
			</h3>

			<div id="product-list">
				<% @products.each_slice(3).each do |slice| %>
					<div class="row">
						<% slice.each do |product| %>
							<div class="col-sm-4 product-card">
								<p class="price pull-right text-right"><%= get_all_currency_symbols[product.current_currency] %> <%= product.price_with_currency %></p>
								<a href="<%= product_path product %>"><img src="<%= product.store_logo_url %>" class="img-circle user-thumb" width="52"/></a>
								<a href="<%= product_path product %>">
									<img class="img-responsive" src="<%= product.product_attachments.first.attachment.small.url if product.product_attachments.first.present? %>" alt="" style="width: 100%;">
								</a>
								<h4>
									<a href="<%= product_path product %>"><%= product.name %></a>
								</h4>
								<a href="<%= product_path product %>">
									<p><%= product.city%>, <%= product.country%></p>
								</a>
							</div>
						<% end %>
					</div>
				<% end %>
			</div>
			<div class="row">
				<form method="POST" action="/products/result" id="trending-form">
					<%= tag(:input, :name => 'authenticity_token', :type => "hidden", :value => form_authenticity_token) %>
					<% ProductCategory.order('id').each do |category| %>
						<input type="hidden" name="category_<%= category.id %>" value="1">
					<% end %>
					<input type="hidden" name="city" value="all cities">
					<div class="col-sm-6 col-md-4 col-lg-4 col-xs-offset-4 all-destinations-sections">
						<button type="submit" class="btn btn-block btn-destination">See All Destinations</button>
					</div>
				</form>
			</div>
			
		</div>
	</div>
</section>

<script>
	$(document).ready(function() { 
  	// initResponsiveHeader(); 
  	$('#trending-location li a').on('click', function(event) {
  		event.preventDefault();
  		var location = $(this).text();
  		var formData = new FormData();
  		formData.append('city', location);
  		$.ajax({
			  url: '/home_products',
			  // dataType: "json",
			  data: formData,
			  cache: false,
			  contentType: false,
			  processData: false,
			  type: 'POST',
			  success: function(data) {
			  	console.log('success');
			  	$('.select-trending').empty();
			  	$('.select-trending').append(location + ' ' + '<span class="caret"></span>');
			  	$('#trending-form input[name=city]').val(location);
			  	$('#product-list').empty();
			  	$('#product-list').append(data);
			  },
			  error: function(error) {
	      	console.log(error);
	      },
	      timeout: 10000
			});
  	})

  	$('#trending-form button').on('click', function() {
  		// $('#trending-form').find('[name="city"]').val('all cities');
  	})

  	

  });
</script>

app/views/home/_top_section.html.erb
<div class="how-it-works-container">
<div class="container-fluid">
<div class="row row-space-top-4 row-space-6">
<div class="col-md-4">
<div class="panel-body text-center">
<div class="how-it-works-image image1"></div>
<h3>Find a Destination</h3>
<p>Travelog makes it easier for you to find the Activities that interest you most.</p>
</div>
</div>
<div class="col-md-4">
<div class="panel-body text-center">
<div class="how-it-works-image image2"></div>
<h3>Choose a Date</h3>
<p>Found the Activities you want? It's only 2 steps away to book your favourite Activites.</p>
</div>
</div>
<div class="col-md-4">
<div class="panel-body text-center">
<div class="how-it-works-image image3"></div>
<h3>Enjoy</h3>
<p>Enjoy you memorable experiences with Travelog!</p>
</div>
</div>
</div>
</div>
</div>

<style type="text/css">
	.how-it-works-container {
    background: #1e3039 url("https://s3-us-west-2.amazonaws.com/travelog/assets/world-map.png") no-repeat scroll 43% 2px;
}

@media (min-width: 1100px)
.container-fluid {
    width: 1045px;
}
.how-it-works-container .how-it-works-image {
    height: 160px;
    margin: 0 auto;
    max-width: 283px;
}
.how-it-works-container .how-it-works-image.image1 {
    background: url("https://s3-us-west-2.amazonaws.com/travelog/assets/travelog-find-a-tour.png") center 0 no-repeat;
    background-size: cover;
}
.how-it-works-container .how-it-works-image.image2 {
    background: url("https://s3-us-west-2.amazonaws.com/travelog/assets/travelog-book-a-tour.png") center 0 no-repeat;
    background-size: cover;
}
.how-it-works-container .how-it-works-image.image3 {
    background: url("https://s3-us-west-2.amazonaws.com/travelog/assets/travelog-how-it-works.png") center 0 no-repeat;
    background-size: cover;
}
.how-it-works-container h3 {
    margin-top: 1em;
    color: #fff;
}
.how-it-works-container p {
    color: #fff;
}
.panel-body>*:last-child {
    margin-bottom: 0;
}
</style>

app/views/home/home_products.html.erb
<div class="row">

  <% @products.each do |product| %>
    <div class="col-sm-6 col-md-4 col-lg-4 product-card">
    <% if product.product_discount != 1 %>
      <p class="price pull-right text-right">
      <span class="discount">

      from <strike><em><%= get_all_currency_symbols[product.current_currency] %></em> <%= product.price_with_currency %></strike>
      </span>
      <br>
      <em><%= get_all_currency_symbols[product.current_currency] %></em> <%= (product.price_with_currency *  product.product_discount).round(2) %></p>
    <% else %>
      <p class="price"><%= get_all_currency_symbols[product.current_currency] %> <%= product.price_with_currency %></p>
    <% end %>
      <a href="<%= product_path product %>"><img src="<%= product.store_logo_url %>" class="img-circle user-thumb" width="52"/></a>

      <p class="star-rating" style="position: absolute;">
                
        <i class="fa fa-star <%= 'empty-star' if product.review_mark <= 0 %>"></i>
        <i class="fa fa-star <%= 'empty-star' if product.review_mark <= 1 %>"></i>
        <i class="fa fa-star <%= 'empty-star' if product.review_mark <= 2 %>"></i>
        <i class="fa fa-star <%= 'empty-star' if product.review_mark <= 3 %>"></i>
        <i class="fa fa-star <%= 'empty-star' if product.review_mark <= 4 %>"></i>
        
      </p>
              
      <div class="img-holder">
        <a href="<%= product_path product %>">
          <img src="<%= product.product_attachments.first.attachment.square.url if product.product_attachments.first.present? %>" alt="<%= product.name %>" style="width: 100%;">
        </a>
      </div>
      <h4>
        <a href="<%= product_path product %>"><%=h truncate(product.name, :length => 30) %></a>
      </h4>
      <a href="<%= product_path product %>">
        <p><%= product.city%>, <%= product.country%></p>
      </a>

    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<%= render 'banner_section' %>

<%= render 'product_section' %>
<%= render 'top_section'%>
<%= render 'explore_section' %>

<script type="text/javascript">
	
</script>


<style>
	section.bg-midnight-blue {
  	z-index: 3;
    position: relative;
    overflow: auto;
	}

	@font-face {
	  font-family: 'Glyphicons Halflings';
	  src: url('/assets/fonts/glyphicons-halflings-regular.otf'); /* IE9 Compat Modes */
	  src: url('/assets/fonts/glyphicons-halflings-regular.otf?#iefix') format('embedded-opentype'), /* IE6-IE8 */
	       url('/assets/fonts/glyphicons-halflings-regular.otf2') format('otf2'), /* Super Modern Browsers */
	       url('/assets/fonts/glyphicons-halflings-regular.otf') format('otf'), /* Pretty Modern Browsers */
	       url('/assets/fonts/glyphicons-halflings-regular.otf')  format('opentype'), /* Safari, Android, iOS */
	       url('/assets/fonts/glyphicons-halflings-regular.otf') format('svg'); /* Legacy iOS */
		  
	}
</style>

app/views/home/index_old.html.erb
<div class="side-collapse-container">
	<section class="header-11-sub bg-midnight-blue navbar-none ">
		<div class="background">
			&nbsp;
		</div>
		<div class="container">
			<div class="row">
				<div class="col-sm-12 text-center">
					<h3>We help you to discover and<br>
						book amazing things to do
					</h3>
					<p>
						Buy experinces not things
					</p>
					<div ng-controller="TestCtrl">
						<form class="form-inline landing-page-search" method="POST" action="/products/result">
							<%= tag(:input, :name => 'authenticity_token', :type => "hidden", :value => form_authenticity_token) %>
							<div class="form-group">
								<input type="text" name="city" class="form-control places-form" id="search-location"  ng-autocomplete="result1" placeholder="Where do you want to go?" autocomplete = "off">
							</div>
							<div class="form-group" ng-controller='DefaultCtrl'>
								<input type="text" id="demo6" name="search_free_text" class="form-control name-form"  auto-complete ui-items="names" ng-model="selected" placeholder="Search Names" autocomplete="off" >
							</div>
							<% ProductCategory.order('id').each do |category| %>
								<input type="hidden" name="category_<%= category.id %>" value="1">
							<% end %>
							<button type="submit" class="btn btn-default search-btn">Search</button>
						</form>
					</div>
					<br>
				</div>
			</div>
		</div>
	</section>
	<div class="container landing-content">
		<!-- Projects Row -->
		<div class="row">
			<div class="col-md-12 text-center content-title">
				<h3>Now trending in Kuala Lumpur</h3>
			</div>
		</div>

			<% @products.each_slice(4).each do |slice| %>
			<div class="row">
			<% slice.each do |product| %>
			<div class="col-md-3 portfolio-item">
				<p class="price"><%= get_all_currency_symbols[product.current_currency] %> <%= product.price_with_currency %></p>
				<a href="<%= product_path product %>"><img src="<%= product.user.store_setting.store_image.store_img.small if product.user.store_setting.store_image.present? %>" class="img-circle user-thumb" width="52"/></a>
				<a href="<%= product_path product %>">
				<img class="img-responsive" src="<%= product.product_attachments.first.attachment.small.url if product.product_attachments.first.present? %>" width="262" alt="">
				</a>
				<h4>
					<a href="<%= product_path product %>"><%= product.name %></a>
				</h4>
				<a href="<%= product_path product %>">
					<p><%= product.city%>, <%= product.country%></p>
				</a>
				</div>
				<% end %>
			</div>
			<% end %>
			
	
		<!-- /.row -->
		<!-- Projects Row -->
		
		<!-- /.row -->
		<div class="row">
			<div class="col-md-12 text-center content-title">
				<h3>Discover</h3>
			</div>
			<div class="col-md-6 portfolio-item">
				<div class="text-overlay big-left">
					<a href="#">Perhentian Island</a>
				</div>
				<div class="overlay-bg"></div>
				<a href="#"  class="overlay-big-left">
				<img class="img-responsive" src="<%= asset_url('9.png') %>" width="570" alt="">
				</a>
			</div>
			<div class="col-md-6 portfolio-item">
				<!--Top Right Image-->
				<div class="text-overlay top-right">
					<a href="#">Yoda Island</a>
				</div>
				<div class="overlay-right-top-bg"></div>
				<a class="overlay-right-top" href="#">
				<img class="img-responsive" src="<%= asset_url('10.png') %>" width="570" alt="">
				</a>
				<!--Bottom Right Image-->
				<div class="text-overlay bottom-right">
					<a href="#">Mount Kinabalu</a>
				</div>
				<div class="overlay-right-bottom-bg"></div>
				<a class="overlay-right-bottom" href="#">
				<img class="img-responsive" src="<%= asset_url('11.png') %>" width="570" alt="">
				</a>
			</div>
			<!--Discover More-->
			<div class="col-md-12 text-center view-more">
				<a href="#" class="view-more-btn">Discover More</a>
			</div>
		</div>
	</div>
	
</div>
<!-- /side-collapse-container  -->
<script>
	function initResponsiveHeader() {
	  var sideslider = $('[data-toggle=collapse-side]');
	  var sel = sideslider.attr('data-target');
	  var sel2 = sideslider.attr('data-target-2');
	  sideslider.click(function(event) {
			$(sel).toggleClass('in');
			$(sel2).toggleClass('out');
	  });

 	}
	
	
	
	$(window).load(function() {
	  $(document).ready(function() { 
	  initResponsiveHeader(); 

	  });
	});
	$(function() {
		function displayResult(item) {
		  $('.alert').show().html('You selected <strong>' + item.value + '</strong>: <strong>' + item.text + '</strong>');
		}
		// $('#demo6').typeahead({
		//   source: [
		// 		'Genting',
		// 		'Zoo Negara',
		// 		'Tioman',
		// 		'Petronas Towers',
		// 		'Batu Caves',
		// 		'Gunung Mulu',
		// 		'Mount Kinabalu',
		// 		'Bako Park',
		// 		'Sunway Lagoon',
		// 		'Pangkor island'],
		//   onSelect: displayResult
		// });

		$('#demo6').typeahead({
		  source: gon.product_categories,
		  onSelect: displayResult
		});

		$('#search-location').typeahead({
			source: gon.search_location_list,
			onSelect: displayResult
		});
	
	});
			
</script>