config/routes.rb
Rails.application.routes.draw do

 
	devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",
																			:registrations => "registrations", :invitations => 'invitations'}

	match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

	get '/users/invitation/invite' => 'users#invite'
	get '/users/fbshare' => 'users#fbshare'
	get '/users/fbshare_accept' => 'users#fbshare_accept'
	root 'home#index'

	post 'home/search' => 'home#search'
	post 'set_currency' => 'application#set_currency'

	post '/home_products' => 'home#home_products'

	post 'twilio/voice' => 'twilio#voice'
	post 'notifications/notify' => 'notifications#notify'
	post 'twilio/status' => 'twilio#status'
	
	resources :products do
		member do
			match "edit_basic",  via: [:get]
			match "edit_description",  via: [:get]
			match "edit_location",  via: [:get]
			match "edit_photo",  via: [:get]
			match "edit_price",  via: [:get]
			post "write_comment" => 'products#write_comment'
			post "remove_comment" => 'products#remove_comment'
			match "set_status", via: [:post]
		end
	end

	resources :cities do
		member do
			match "category", via: [:get]
		end
	end

	resource :place do
		

		get ':slug' => 'places#search_place'
		post ':slug' => 'places#search_place'
	end
	
	resources :store
	resources :product_attachments
	resources :store_images
	resources :user_avatars
	resources :profile_documents
	resources :account_documents

	post 'invoices/new' => 'invoices#new'
	get 'invoices/success_checkout' => "invoices/success_checkout"
	get 'invoices/cancel_checkout' => "invoices/cancel_checkout"

	get 'invoices/checkout/:slug' => 'invoices#display', :as => 'slug_invoice'
	resources :invoices do
		member do
			match 'abandoned_checkout', via: [:get]
		end
	end
	resource :invoices do

	end

	get 'become_merchant' => 'users#become_merchant'
	post 'become_merchant' => 'users#become_merchant'
	get 'merchant' => 'users#merchant_landing'
	get 'profile' => 'users#profile'
	post 'profile' => 'users#profile'
	patch 'profile' => 'users#profile'
	get 'profile/avatar' => 'users#profile_avatar'
	post 'profile/avatar' => 'users#profile_avatar'
	patch 'profile/avatar' => 'users#profile_avatar'
	get 'profile/security' => 'users#profile_security'
	post 'profile/security' => 'users#profile_security'
	patch 'profile/security' => 'users#profile_security'

	resource :user do
		match 'account_document', via: [:get, :post, :patch]
		match 'getting_paid', via: [:get, :post, :patch]
	end

	get 'accounts' => 'users#accounts'
	post 'accounts' => 'users#accounts'
	patch 'accounts' => 'users#accounts'
	get 'accounts/photo' => 'users#accounts_photo'
	post 'accounts/photo' => 'users#accounts_photo'
	patch 'accounts/photo' => 'users#accounts_photo'

	get 'profile/photos' => 'users#photos'
	post 'profile/photos' => 'users#photos'
	post 'complete_merchant' => 'users#complete_merchant'
	get 'verify_document' => 'users#verify_merchant'
	get 'dashboard' => 'users#dashboard'

	get 'about' => 'users#about'
	get 'blog' => 'users#blog'
	get 'career' => 'users#career'
	get 'contact' => 'users#contact'
	get 'press' => 'users#press'
	get 'terms' => 'users#terms'
	get 'policy' => 'users#policy'
	get 'help' => 'users#help'

	get 'users/verify_store_username' => 'users#verify_store_username'

	resources :trips do
		post 'update_status' => 'trips#update_status'
	end

	resource :trips do
		get 'checkout/:slug' => 'trips#display', :as => 'slug_trip_checkout'
	end

	resources :reservations do
		post 'update_status' => 'reservations#update_status'
		
	end
	resource :reservations do
		get 'checkout/:slug' => 'reservations#display', :as => 'slug_reservation_checkout'
	end

	get 'reservations/show/:slug' => 'reservations#display', :as => 'slug_reservation'

	resource :coupons do
		match 'get_coupon', via: [:get, :post]
	end

	resource :comments do
		match 'create_comment', via: [:post]
		match 'remove_comment', via: [:post]
		match 'update_comment', via: [:post]
	end
	

	namespace :api, defaults: {format: 'json'}  do
		namespace :v1 do
			resource :users do
				match 'login', via: [:post]
				match 'signup', via: [:post]
			end
			get 'profile' => 'users#profile'
		end
	end

end

app/controllers/products_controller.rb
require 'money/bank/google_currency'


class ProductsController < ApplicationController

	before_action :set_product, only: [:show, :edit, :update, :destroy, :write_comment, :remove_comment, :set_status]
	before_action :set_product_widget, only: [:edit_basic, :edit_description, :edit_location, :edit_photo, :edit_price]
	skip_before_action :authenticate_user!, only: [:result, :show]

	def layout_by_resource
		"product"
	end

	def index
		if current_user.status == 'merchant'
			# if current_user.merchant_status == 'verified'
				
			# else
			# 	redirect_to verify_document_path
			# end

			product_arel_table = Product.arel_table

			@products = current_user.products

			if current_user.merchant_status == 'verified'
				@listed_products = @products.where(:step => 5, :status => 1).includes(:product_attachments).includes(:product_reviews).order("created_at desc")

				@unlisted_products = @products.where(
				  product_arel_table[:step].not_eq(5).
				  or(product_arel_table[:status].not_eq(1))
				).includes(:product_attachments).includes(:product_reviews).order("created_at desc")

			else
				# for the non-verified user
				@listed_products = @products.where(:step => 5, :status => 1, :verification => 1).includes(:product_attachments).includes(:product_reviews).order("created_at desc")

				@unlisted_products = @products.where(product_arel_table[:step].not_eq(5).or(product_arel_table[:status].not_eq(1)).or(product_arel_table[:verification].not_eq(1))
				).includes(:product_attachments).includes(:product_reviews).order("created_at desc")				
			end

			# @unlisted_products = @products.where.not(:step => 5).includes(:product_attachments).includes(:product_reviews).order("created_at desc")


			unless current_user.merchant_status == 'verified'
				@is_verify_need = true
			end

			@unlisted_products.each do |product|
				product.set_extra_attributes
			end

			@listed_products.each do |product|
				product.set_extra_attributes
			end
		else
			redirect_to root_path
		end
	end

	def show
		@user = @product.user
		# @other_products = Product.public_active.order('random()').limit(4).includes(:product_attachments).includes(:product_reviews)
		@same_city_products = Product.city_products(@product.city, @product.id, 4)

		@same_city_products.each do |product|
			product.set_extra_attributes
		end
		set_product_currency_attributes(@same_city_products)

		same_city_product_count = @same_city_products.count

		if same_city_product_count < 4
			@kl_products = Product.city_products('Kuala Lumpur', @product.id, 4 - same_city_product_count)
			@kl_products.each do |product|
				product.set_extra_attributes
			end
			set_product_currency_attributes(@kl_products)
		end
		
		@product_cover_image_url = @product.product_attachments.order('id')[0].attachment.url if @product.product_attachments.count > 0
		gon.product_cover_image_url = @product.product_attachments.order('id')[0].attachment.large.url if @product.product_attachments.count > 0
		@is_variants = true if @product.variants.count > 0

		if @product.currency != session[:currency]
			rate = session["currency-convert-#{session[:currency]}"].to_f / session["currency-convert-#{@product.currency}"].to_f
		else
			rate = 1.0
		end

		@product.price_with_currency = (@product.price_cents * rate / 100).round(2)
		@product.current_currency = session[:currency]
		@product.variants.each do |variant|
			variant.price_with_currency = (variant.price_cents * rate / 100).round(2)
		end
		
		gon.variants = @product.variants if @is_variants

		
		@current_currency = get_all_currency_symbols[session[:currency]]

		# set params for product reivews
		if user_signed_in?
			@product_reviews = @product.product_reviews.where(:user_id => current_user.id)
			@product_reviews += @product.product_reviews.where.not(:user_id => current_user.id).order('user_id')  
		else
			@product_reviews = @product.product_reviews
		end
		
		@total_review_count = @product_reviews.count

		# set the review mark
		@product.set_review
		
		@product_reviews = Kaminari.paginate_array(@product_reviews).page(params[:page]).per(10)

		@product_reviews.each do |product_review|
			product_review.set_avatar_url
		end

		@original_url = request.original_url

		
		@product_discount = 1 - @product.discount.to_f / 100

		render :layout => "product_detail"
	end

	def write_comment
		message = params[:message]
		product_review = ProductReview.where(:user_id => current_user.id, :product_id => @product.id).first
		product_review = ProductReview.new({:user_id => current_user.id, :product_id => @product.id}) if product_review.blank?
		product_review.message = message
		product_review.rating_stars = params["rating-stars"].to_i
		if product_review.save
			product_name = @product.name
			# UserMailer.delay_for(10.minutes).write_review(current_user, @product, message)
			redirect_to product_path @product
		else
			redirect_to root_path
		end
	end

	def remove_comment
		product_review = ProductReview.find_by_id(params[:review_id])
		if product_review.present? && product_review.product_id == @product.id && product_review.user_id == current_user.id
			product_review.destroy
			render :json => {:status => 'success'}.to_json
		else
			render :json => {:status => 'fail'}.to_json
		end
	end

	def new
		# if current_user.status == 'merchant' && current_user.merchant_status == 'verified'
		if current_user.status == 'merchant'
			@product = Product.new
			@categories = ProductCategory.all
			@product_attachment = @product.product_attachments.build
			@product_attachments = ProductAttachment.all
			@show_section = 'basic'
			render :layout => 'product_new'
		else
			redirect_to root_path
		end
	end

	def create
		@product = Product.new(product_params)
		@product.user = current_user
		respond_to do |format|

			if params[:product].present?
				unless @product.save
					# format.html { render :new }
					
					format.html { redirect_to new_product_path }
					format.json { render json: @product_attachment.errors, status: :unprocessable_entity }
				end
			end
			
			param_variants = params[:variant]
			if param_variants.present?
				param_variants.delete_if{|sa| !sa.stringify_keys['name'].present? }
			else
				param_variants = []
			end
			
			if param_variants.count > 0
				base_price_cents = (param_variants[0][:price_cents].to_f * 100).to_i
				param_variants.each do |param_variant|
					if param_variant[:name].present?
						variant = Variant.new
						variant.name = param_variant[:name]
						variant.price_cents = (param_variant[:price_cents].to_f * 100).to_i
						variant.product = @product
						variant.min_count = param_variant[:min_count].to_i if param_variant[:min_count].present?
						variant.max_count = param_variant[:max_count].to_i if param_variant[:max_count].present?
						if variant.min_count.present? && variant.max_count.present? && variant.max_count < variant.min_count
							variant.max_count = variant.min_count
						end
						variant.save  
					end
				end
				@product.price_cents = base_price_cents
			end

			if params[:product_attachment].present?
				params[:product_attachment]['id'].each do |a|
					product_attachment = ProductAttachment.find(a)
					if product_attachment.present?
						product_attachment.product = @product
						product_attachment.save
					end
				end
			end
			

			step_param = params["step-param"]
			case step_param
			when "basic"
				if @product.step == 'basic'
					@product.step = 'description'
					@product.save
				end
				format.html { redirect_to edit_description_product_path @product, :flash => { :notice => "Added a new product successfully." } }
				format.json { render :show, status: :ok, location: @product_attachment }
			when "description"
				format.html { redirect_to edit_location_product_path @product }
				format.json { render :show, status: :ok, location: @product_attachment }
			when "location"
				format.html { redirect_to edit_photo_product_path @product }
				format.json { render :show, status: :ok, location: @product_attachment }
			when "photo"
				format.html { redirect_to edit_price_product_path @product }
				format.json { render :show, status: :ok, location: @product_attachment }
			else
				format.html { redirect_to products_path }
				format.json { render :show, status: :ok, location: @product_attachment }
			end
			
		end
	end

	def edit
		# @categories = ProductCategory.all
		# render :layout => 'product_new'
		case @product.step
		when 'basic'
			redirect_to edit_basic_product_path @product
		when 'description'
			redirect_to edit_description_product_path @product
		when 'location'
			redirect_to edit_location_product_path @product
		when 'photo'
			redirect_to edit_photo_product_path @product
		when 'price'
			redirect_to edit_price_product_path @product
		else
			redirect_to edit_basic_product_path @product
		end
		
	end

	def edit_basic
		@show_section = 'basic'
		render :layout => 'product_new', :template => 'products/edit'
	end

	def edit_description
		@show_section = 'description'
		render :layout => 'product_new', :template => 'products/edit'
	end

	def edit_location
		@show_section = 'location'
		render :layout => 'product_new', :template => 'products/edit'
	end

	def edit_photo
		@show_section = 'photo'
		render :layout => 'product_new', :template => 'products/edit'
	end

	def edit_price
		gon.product_status = @product.status
		@show_section = 'price'
		render :layout => 'product_new', :template => 'products/edit'
	end

	def set_status
		@product.status = params[:status]
		if @product.save
			render :json => @product, status: 200
		else
			render json: @product.errors, status: :unprocessable_entity
		end
	end

	# PATCH/PUT /products/1
	# PATCH/PUT /products/1.json
	def update
		respond_to do |format|
			if params[:product].present?
				unless @product.update_attributes(product_params)
					format.html { return render :edit }
					format.json { return render json: @product_attachment.errors, status: :unprocessable_entity }
				end
			end

			# update frinedly url

app/helpers/products_helper.rb
module ProductsHelper
	
end

app/views/products/_gallery_details.html.erb
<section class="gallery">
	<div>
		<div class="container">
			<div class="row">
				<div id="lightgallery" class="col-md-7 detailpage-images-gallery" >
					<% if @product.product_attachments.present? && @product.product_attachments.count > 0 %>
						<% @product.product_attachments.each_with_index do |attachment, index| %>
							<% if index == 0 %>

								<div class="col-sm-6 col-md-6 topleftimg <%='hidden-xs' if index != @product.product_attachments.count - 1 %>" data-responsive="<%= attachment.attachment.large.url %>" data-src="<%= attachment.attachment.large.url %>" data-sub-html="<%= @product.highlight %>">                
									<a href="">
										<img src="<%= attachment.attachment.small.url %>" class="img-responsive">
									</a>
								</div>
							<% elsif index == 1 %>

								<div class="col-sm-6 col-md-6 toprightimg <%='hidden-xs' if index != @product.product_attachments.count - 1 %>" data-responsive="<%= attachment.attachment.large.url %>" data-src="<%= attachment.attachment.large.url %>" data-sub-html="<%= @product.highlight %>">                
									<a href="">
										<img src="<%= attachment.attachment.small.url %>" class="img-responsive">
									</a>
								</div>
							<% elsif index == 2 %>

								<div class="col-sm-4 col-md-4 bottomleftimg <%='hidden-xs' if index != @product.product_attachments.count - 1 %>" data-responsive="<%= attachment.attachment.large.url %>" data-src="<%= attachment.attachment.large.url %>" data-sub-html="<%= @product.highlight %>">                
									<a href="">
										<img src="<%= attachment.attachment.small.url %>" class="img-responsive">
									</a>
								</div>
							<% elsif index == 3 %>

								<div class="col-sm-4 col-md-4 bottomcentreimg <%='hidden-xs' if index != @product.product_attachments.count - 1 %>" data-responsive="<%= attachment.attachment.large.url %>" data-src="<%= attachment.attachment.large.url %>" data-sub-html="<%= @product.highlight %>">                
									<a href="">
										<img src="<%= attachment.attachment.small.url %>" class="img-responsive">
									</a>
								</div>
							<% elsif index == 4 %>
								<div class="col-sm-4 col-md-4 bottomrightimg <%='hidden-xs' if index != @product.product_attachments.count - 1 %>" data-responsive="<%= attachment.attachment.large.url %>" data-src="<%= attachment.attachment.large.url %>" data-sub-html="<%= @product.highlight %>">
									<div class="gallery-overlay-cover"></div>
									<a href="">
										<img src="<%= attachment.attachment.small.url %>" class="img-responsive">
									</a>
								</div>
							<% else %>
							<% end %>
							
						<% end %>
					<% end %>

				</div>
			</div>
			<!--gallery-->   
		</div>

	</div>
</section>

<style>
	.lg-sub-html {
		background: white;
		max-height: 100px;
	}
	.gallery-overlay-cover:hover {
	  cursor: pointer;
	}
</style>

app/views/products/_nav_second.html.erb
<nav class="navbar navbar-static-top nav-second-profile sub-header-fixed">
	<div class="container">
		<div id="" class="">
			<ul class="nav navbar-nav">
				<li class="<%= 'active' if obj == 'dashboard' %>"><a href="/dashboard">Dashboard</a></li>
				<!-- <li><a href="#">Inbox</a></li> -->
				<li class="<%= 'active' if obj == 'listing' %>"><a href="/products">Listing</a></li>
				<li class="<%= 'active' if obj == 'trips' %>"><a href="/trips">Trips</a></li>
				<li class="<%= 'active' if obj == 'profile' %>"><%= link_to 'Profile', profile_path %></li>
				<% if current_user.status == 'merchant' %>
					<li class="<%= 'active' if obj == 'accounts' %>"><%= link_to 'Accounts', accounts_path %></li>
				<% end %>
			</ul>
		</div>
		<!--/.nav-collapse -->
	</div>
</nav>

app/views/products/_nav_second_backup.html.erb
<nav class="navbar navbar-fixed-top nav-second-profile">
	<div class="container">
		<div class="row">
			<div class="col-sm-3 col-md-2 second-sidebar">
				<ul class="nav navbar-nav ">
					<li>
						<% if @product.name.present? %>
							<%= truncate(strip_tags(@product.name), length: 31, escape: false) %>
						<% else %>
							Places, for traveller
						<% end %>
						
					</li>
				</ul>
			</div>
		</div>
		<!-- <div id="" class="">
			<ul class="nav navbar-nav">
				<li><a href="#">Places, for traveller in Kuala Lumpur</a></li>
			</ul>
		</div> -->
		<!--/.nav-collapse -->
	</div>
</nav>

<style>
	.second-sidebar {
		position: fixed;
    /*top: 74px;*/
    top: 0;
    left: 0;
    z-index: 1000;
    display: block;
    overflow-x: hidden;
    overflow-y: hidden;
    border-right: 1px solid #eee;
    height: 44px;
	}

	.nav-second-profile .navbar-nav > li {
		padding-left: 0;
		padding-top: 14px;
	}
</style>

app/views/products/_product_details.html.erb
<section class="header-10-sub v-center ">
	<div class="background">
		
	</div>
	<div>
		<div class="container">
			<div class="hero-unit">

			</div>
		</div>
	</div>
</section>

<!-- About Merchant  -->
<section class="content-7 aboutmerchant"  itemscope itemtype="http://schema.org/Product">


	<div class="row">
		
		<!-- start Show up on responsive small booking  -->
		<%= render 'responsive_booking_section' %>
		<!-- end Show up on responsive small booking -->


		<!--booking-->
		<%= render 'about_merchant_section' %>

	</div>
</section>

<!-- About listing -->
<section class="content-8 aboutlisting">
	<div class="container">
		About this listing. 
		<% if @product.user == current_user %>
			(<a href="/products/<%= @product.id %>/edit"><span>Edit Listing</span></a>)
		<% end %>
	</div>
</section>

<!-- content-8  -->

<section class="greysection aboutproduct">
	<div class="container">

		<div class="row">

			<div class="col-xs-12 col-md-7">
				<%= @product.description.html_safe if @product.description.present? %>
			</div>
		</div>                        

	</div>
</section>

<script>
	$(document).ready(function() {

	})
</script>

<style>
	/* style for adjusting validation mark */
	.fv-form-bootstrap .fv-icon-no-label {
		right: 15px;
	}
	label.refund, p.refund {
		color: #7f8c8d;
	}

	.BVRRRatingNormalOutOf {
		display: none;
	}

	p.refund.refund-sub {
		margin-left: 15px;
	}

	section.aboutproduct, section.gallery {
    background: #F5F5F5;
	}

	section.aboutlisting {
		background: #F5F5F5;
		min-height: initial;
		padding: 40px 0;
		border-top: 1px solid #dce0e0;
	}
	section.aboutlisting .container {
		color: #333;
		font-size: 20px;
		text-align: left;
	}

	section.aboutlisting .container span {
		color: rgb(226, 1, 1);
	}
</style>

app/views/products/index.html.erb
<%= render "shared/settings_nav", :obj => 'listing' %>
<div class="side-collapse-container">
	<section class="header-11-sub profile-page">
		<div class="container">
			<div class="row ">
				<div class="col-sm-3 col-md-3 sidebar-profile-dashboard">
					<%= render "shared/listing_left_nav", :obj => 'listings' %>
				</div>
				<div class="col-md-9">
					<% if @is_verify_need %>
						<div class="row">
							<div class="col-sm-12">
								<h6>
									Your Merchant signup status are Pending. To verify your Merchant signup, you need to submit a relavant documents.
								</h6>
								<a href="/user/account_document" class="btn btn-success btn-proceed btn-next pull-left btn-verify">Verify</a>
							</div>
						</div>
					<% end %>
					<div class="row" style="margin-bottom: 15px;">
						<div class="col-md-10">
							
						</div>
						<div class="col-md-2">
							<select class=" form-control" title="Dropdown" id="listed-change">
								<option value="all">All</option>
								<option value="listed">Listed</option>
								<option value="unlisted">Unlisted</option> 
							</select>
							
						</div>
					</div>

					<div class="panel panel-default listed">
						<div class="panel-heading"> 
							<h5 class="panel-title">
								Listed
							</h5> 
						</div> 
						<div class="panel-body">
							<div class="row">
								<% @listed_products.each_with_index do |product, index|%>
									<div class="col-md-12">
										<div class="col-md-3">
											<a href="<%= edit_product_path product %>" class="thumbnail">
												<% if product.product_overview_url.present? %>
													<img src="<%= product.product_overview_url %>" alt="...">
												<% else %>
													<img src="<%= asset_url('placehold_200_200.png') %>" alt="...">
												<% end %>
											</a>
										</div>

										<div class="col-md-6">
											<h5><%= product.name %>, for traveller in <%= product.city %></h5>
											<a href="/products/<%= product.id %>/edit">Manage Listing and Price</a>
										</div>

										<div class="col-md-3">
										
											<select class=" form-control <%= product.status %> product-status" title="Dropdown" id="status-change" product-id="<%= product.id %>">
												<option value="enable" <%= 'selected' if product.status == 'enable' %>>Listed</option>
												<option value="disable" <%= 'selected' if product.status == 'disable' %>>Unlisted</option>
											</select>
											
										</div>
									</div>
									<% unless index == @listed_products.count - 1 %>
										<!-- <hr> -->
									<% end %>
								<% end %>
								<% if @listed_products.count == 0 %>
									<div class="col-md-12">
										<div class="col-md-3">
											<a href="#" class="thumbnail">
												<img src="<%= asset_url('placehold_200_200.png') %>" alt="...">
											</a>
										</div>

										<div class="col-md-6">
											<h5>There is no listed product.</h5>
											<!-- <p>Manage Listing and Calendar</p> -->
										</div>

										<div class="col-md-3">
											
										</div>
									</div>
								<% end %>
							</div>
						</div>
					</div>

					<div class="panel panel-default unlisted">
						<div class="panel-heading"> 
							<h5 class="panel-title">
								Unlisted
							</h5> 
						</div> 
						<div class="panel-body">
							<div class="row">
								<% @unlisted_products.each_with_index do |product, index|%>
									<div class="col-md-12">
										<div class="col-md-3">
											<a href="<%= edit_product_path product %>" class="thumbnail">
												<% if product.product_overview_url.present? %>
													<img src="<%= product.product_overview_url %>" alt="...">
												<% else %>
													<img src="<%= asset_url('placehold_200_200.png') %>" alt="...">
												<% end %>
											</a>
										</div>

										<div class="col-md-6">
											<h5><%= product.name %>, for traveller in <%= product.city %></h5>
											<p>Manage Listing and Calendar</p>
										</div>

										<div  class="col-md-3">
											
											<% if product.step == 'complete' %>
												<select class=" form-control <%= product.status %> product-status" title="Dropdown" id="status-change" product-id="<%= product.id %>">
													<option value="enable" <%= 'selected' if product.status == 'enable' %>>Listed</option>
													<option value="disable" <%= 'selected' if product.status == 'disable' %>>Unlisted</option>
												</select>
												<!-- verification notify -->
												<% if current_user.merchant_status == 'pending' && product.status == 'enable' %>
													<p class="product-verification <%= product.verification %>"><%= product.verification.capitalize %> Verification</p>
												<% end %>
											<% else %>
												<a href="<%= edit_product_path product %>" class="btn btn-default btn-list" >
													<%= 5 - Product.steps[product.step] %> Steps to list
												</a>
											<% end %>
										  
										</div>
									</div>
									<% unless index == @unlisted_products.count - 1 %>
										<!-- <hr> -->
									<% end %>
								<% end %>
								<% if @unlisted_products.count == 0 %>
									<div class="col-md-12">
										<div class="col-md-3">
											<a href="#" class="thumbnail">
												<img src="<%= asset_url('placehold_200_200.png') %>" alt="...">
											</a>
										</div>

										<div class="col-md-6">
											<h5>There is no unlisted product.</h5>
											<!-- <p>Manage Listing and Calendar</p> -->
										</div>

										<div class="col-md-3">
											
										</div>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- full-box-border -->
</div>
<!-- /side-collapse-container  -->

<!-- customized by me -->
<style>
	.btn-default {
		padding: 10px 25px;
	}
	.product-status.enable {
		border-color: green;
    color: green;
	}
	.product-status.disable {
		border-color: red;
    color: red;
	}
	.status-notice {
		color: green;
	}
	.product-verification {
		color: red;
    margin: 5px 0 0 15px;
	}
</style>



<script>

	$(document).ready(function() {
		$('#listed-change').on('change', function() {
			var listed_status = $(this).val();
			if(listed_status == 'listed') {
				$('.panel.listed').fadeIn('slow');
				$('.panel.unlisted').fadeOut('slow');
			} else if (listed_status == 'unlisted') {
				$('.panel.listed').fadeOut('slow');
				$('.panel.unlisted').fadeIn('slow');
			} else {
				$('.panel.listed').fadeIn('slow');
				$('.panel.unlisted').fadeIn('slow');
			}
		})

		$(document).on('change', '.product-status', function() {

			var formData = new FormData();
			
			formData.append('status', $(this).val());
			url = $(this).attr('product-id');
			url = "/products/" + url + "/set_status";
			$this = $(this);

			var append_html = '<p class="status-notice">Saving...</p>';
			$this.before(append_html);

			var merchant_status = "<%= current_user.merchant_status %>";
			$_this = $(this);
			
			$.ajax({
				url: url,
				dataType: "json",
				data: formData,
				cache: false,
				contentType: false,
				processData: false,
				type: 'POST',
				success: function(data) {
					console.log('success');
					$this.removeClass('enable').removeClass('disable').addClass(data.status);
					$this.parent().find('.status-notice').text('Saved!').fadeOut('slow');

					if (merchant_status == 'pending' && data.verification != 'accepted') {
						$_this.parent().find('p.product-verification').remove();

						if (data.status == 'enable') {
							append_html = '<p class="product-verification ' + data.verification.capitalizeFirstLetter() + '">' + data.verification.capitalizeFirstLetter() + " Verification</p>";
							$_this.parent().append(append_html);
						};
						
					};
				},
				error: function(error) {
					console.log(error);
					
				},
				timeout: 500000
			});

		})

	})


</script>