config/routes.rb
Rails.application.routes.draw do

 
	devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",
																			:registrations => "registrations", :invitations => 'invitations'}

	match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

	get '/users/invitation/invite' => 'users#invite'
	get '/users/fbshare' => 'users#fbshare'
	get '/users/fbshare_accept' => 'users#fbshare_accept'
	root 'home#index'

	post 'home/search' => 'home#search'
	post 'set_currency' => 'application#set_currency'

	post '/home_products' => 'home#home_products'

	post 'twilio/voice' => 'twilio#voice'
	post 'notifications/notify' => 'notifications#notify'
	post 'twilio/status' => 'twilio#status'
	
	resources :products do
		member do
			match "edit_basic",  via: [:get]
			match "edit_description",  via: [:get]
			match "edit_location",  via: [:get]
			match "edit_photo",  via: [:get]
			match "edit_price",  via: [:get]
			post "write_comment" => 'products#write_comment'
			post "remove_comment" => 'products#remove_comment'
			match "set_status", via: [:post]
		end
	end

	resources :cities do
		member do
			match "category", via: [:get]
		end
	end

	resource :place do
		

		get ':slug' => 'places#search_place'
		post ':slug' => 'places#search_place'
	end
	
	resources :store
	resources :product_attachments
	resources :store_images
	resources :user_avatars
	resources :profile_documents
	resources :account_documents

	post 'invoices/new' => 'invoices#new'
	get 'invoices/success_checkout' => "invoices/success_checkout"
	get 'invoices/cancel_checkout' => "invoices/cancel_checkout"

	get 'invoices/checkout/:slug' => 'invoices#display', :as => 'slug_invoice'
	resources :invoices do
		member do
			match 'abandoned_checkout', via: [:get]
		end
	end
	resource :invoices do

	end

	get 'become_merchant' => 'users#become_merchant'
	post 'become_merchant' => 'users#become_merchant'
	get 'merchant' => 'users#merchant_landing'
	get 'profile' => 'users#profile'
	post 'profile' => 'users#profile'
	patch 'profile' => 'users#profile'
	get 'profile/avatar' => 'users#profile_avatar'
	post 'profile/avatar' => 'users#profile_avatar'
	patch 'profile/avatar' => 'users#profile_avatar'
	get 'profile/security' => 'users#profile_security'
	post 'profile/security' => 'users#profile_security'
	patch 'profile/security' => 'users#profile_security'

	resource :user do
		match 'account_document', via: [:get, :post, :patch]
		match 'getting_paid', via: [:get, :post, :patch]
	end

	get 'accounts' => 'users#accounts'
	post 'accounts' => 'users#accounts'
	patch 'accounts' => 'users#accounts'
	get 'accounts/photo' => 'users#accounts_photo'
	post 'accounts/photo' => 'users#accounts_photo'
	patch 'accounts/photo' => 'users#accounts_photo'

	get 'profile/photos' => 'users#photos'
	post 'profile/photos' => 'users#photos'
	post 'complete_merchant' => 'users#complete_merchant'
	get 'verify_document' => 'users#verify_merchant'
	get 'dashboard' => 'users#dashboard'

	get 'about' => 'users#about'
	get 'blog' => 'users#blog'
	get 'career' => 'users#career'
	get 'contact' => 'users#contact'
	get 'press' => 'users#press'
	get 'terms' => 'users#terms'
	get 'policy' => 'users#policy'
	get 'help' => 'users#help'

	get 'users/verify_store_username' => 'users#verify_store_username'

	resources :trips do
		post 'update_status' => 'trips#update_status'
	end

	resource :trips do
		get 'checkout/:slug' => 'trips#display', :as => 'slug_trip_checkout'
	end

	resources :reservations do
		post 'update_status' => 'reservations#update_status'
		
	end
	resource :reservations do
		get 'checkout/:slug' => 'reservations#display', :as => 'slug_reservation_checkout'
	end

	get 'reservations/show/:slug' => 'reservations#display', :as => 'slug_reservation'

	resource :coupons do
		match 'get_coupon', via: [:get, :post]
	end

	resource :comments do
		match 'create_comment', via: [:post]
		match 'remove_comment', via: [:post]
		match 'update_comment', via: [:post]
	end
	

	namespace :api, defaults: {format: 'json'}  do
		namespace :v1 do
			resource :users do
				match 'login', via: [:post]
				match 'signup', via: [:post]
			end
			get 'profile' => 'users#profile'
		end
	end

end

app/helpers/layout_helper.rb
module LayoutHelper
	include ApplicationHelper

	def title(page_title, show_title = true)
		content_for(:title) { page_title.to_s }
		@show_title = show_title
	end
	
	def page_title(text=nil)
		return text unless text.blank?
		site_name
	end
end

app/views/layouts/_fixed_header.html.erb
<header class="header-10" style="position: fixed;">
	<div class="container">
		<div class="navbar col-sm-12" role="navigation">
			<div class="navbar-header nav-dark">
				<button type="button" class="navbar-toggle"></button>
				<a class="brand" href="/">
					<%= render 'layouts/brand_svg' %>
				</a>
			</div>
			<div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
				<% if @is_search %>
					<form class="navbar-form navbar-right navsearch-form" id="result-filter" method="POST" action="/products/result">
						<%= tag(:input, :name => 'authenticity_token', :type => "hidden", :value => form_authenticity_token) %>
						<% ProductCategory.order('id').each do |category| %>
							<input type="hidden" name="category_<%= category.id %>" value="<%= "1" if @categories["category_#{category.id}"].present? && @categories["category_#{category.id}"].to_i %>">
						<% end %>

						<div class="form-group">
							<input type="text" class="form-control navsearch" style="width: 440px;" id="search-location" name="city" placeholder="Search" value="<%= @city %>">
						</div>
					</form>
				<% end %>
				<ul class="nav pull-left">
					<% if user_signed_in? %>
						<% unless current_user.status == 'merchant' %>
							<li><%= link_to "Become a merchant", become_merchant_path %></li>
						<% end %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle dropdownselectactive" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								<% if current_user.profile.present? && current_user.profile.first_name.present? %>
									<%= current_user.profile.first_name %>
								<% else %>
									<%= current_user.email %>
								<% end %>
								<% if current_user.get_avatar_url.present? %>
									<img src="<%= current_user.get_avatar_url %>" width="40" height = "40" class="img-circle profile-nav"/>
								<% else %>
									<img src="<%= asset_url('default-avatar.png') %>" width="40" height = "40" class="img-circle profile-nav"/>
								<% end %>
								<!-- <img src="https://s3.amazonaws.com/uifaces/faces/twitter/jeanniehuang/128.jpg" width="40" class="img-circle profile-nav"/> -->
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to 'Edit Profile', profile_path  %></li>
								<li><a href="/users/invitation/new">Travel Credit</a></li>
								<% if current_user.status == 'merchant' %>
									<li><%= link_to 'Store Settings', accounts_path %></li>
								<% end %>
								<li><a rel="nofollow" data-method="delete" href="/users/sign_out">Log Out</a></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Become a merchant", become_merchant_path %></li>
						<li><%= link_to "Login", new_user_session_path() %></li>
						<li><%= link_to "Sign Up", new_user_registration_path %></li>
					<% end %>

				</ul>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_header.html.erb
<header class="header-10">
	<div class="container">
		<div class="navbar col-sm-12" role="navigation">
			<div class="navbar-header nav-dark">
				<button type="button" class="navbar-toggle"></button>
				<a class="brand" href="/">
					<%= render 'layouts/brand_svg' %>
				</a>
			</div>
			<div class="collapse navbar-collapse pull-right profilex" id="bs-example-navbar-collapse-1">
				<ul class="nav pull-left">
					<% if user_signed_in? %>
						<li class="visible-xs visible-sm hidden-md hidden-lg">
							<a href="#" class="sidebarprofile">
								<% if current_user.get_avatar_url.present? %>
									<img src="<%= current_user.get_avatar_url %>" width="40" height = "40" class="img-circle profile-nav"/>
								<% else %>
									<img src="<%= asset_url('default-avatar.png') %>" width="40" height = "40" class="img-circle profile-nav"/>
								<% end %>
								<% if current_user.profile.present? && current_user.profile.first_name.present? %>
									<%= current_user.profile.first_name %>
								<% else %>
									<%= current_user.email %>
								<% end %>
							</a>
						</li>

						<% unless current_user.status == 'merchant' %>
							<li class=" hidden-xs hidden-sm"><%= link_to "Become a Merchant", merchant_path %></li>
						<% end %>

						<li class="visible-xs visible-sm"><%= link_to 'Edit Profile', profile_path  %></li>
						<li class="visible-xs visible-sm"><a href="/users/invitation/new">Invite Friends</a></li>
						<% if current_user.status == 'merchant' %>
							<li class="visible-xs visible-sm"><%= link_to 'Store Settings', accounts_path %></li>
						<% end %>
						<li class="visible-xs visible-sm"><a rel="nofollow" data-method="delete" href="/users/sign_out">Log Out</a></li>
						
						<!--dropdown x-->
						<li class="dropdown hidden-xs hidden-sm">
							<a href="#" class="dropdown-toggle dropdownselectactive" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								<% if current_user.profile.present? && current_user.profile.first_name.present? %>
									<%= current_user.profile.first_name %>
								<% else %>
									<%= current_user.email %>
								<% end %>

								<% if current_user.get_avatar_url.present? %>
									<img src="<%= current_user.get_avatar_url %>" width="40" height = "40" class="img-circle profile-nav"/>
								<% else %>
									<img src="<%= asset_url('default-avatar.png') %>" width="40" height = "40" class="img-circle profile-nav"/>
								<% end %>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to 'Edit Profile', profile_path  %></li>
								<li><%= link_to 'Trips', trips_path %></li>
								<% if current_user.status == 'merchant' %>
									<li><%= link_to 'Manage Listings', products_path %></li>
									<li><%= link_to 'Store Settings', accounts_path %></li>
								<% end %>
								<li><a href="/users/invitation/new">Travel Credit</a></li>
								<li><a rel="nofollow" data-method="delete" href="/users/sign_out">Log Out</a></li>
							</ul>
						</li>
						<!--dropdown x-->
					<% else %>
						<li class=" hidden-xs hidden-sm"><%= link_to "Become a Merchant", merchant_path %></li>
						<li class=" hidden-xs hidden-sm"><%= link_to "Login", new_user_session_path() %></li>
						<li class=" hidden-xs hidden-sm"><%= link_to "Sign Up", new_user_registration_path %></li>

						<li class=" visible-xs visible-sm"><%= link_to "Login", new_user_session_path() %></li>
						<li class=" visible-xs visible-sm"><%= link_to "Sign Up", new_user_registration_path %></li>

						<!--dropdown x-->
						<li class="dropdown hidden-xs hidden-sm">
							<ul class="dropdown-menu">
								<li><%= link_to "Become a merchant", become_merchant_path %></li>
								<li><%= link_to "Login", new_user_session_path() %></li>
								<li><%= link_to "Sign Up", new_user_registration_path %></li>
							</ul>
						</li>
						<!--dropdown x-->
					<% end %>

					
				</ul>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_header_backup.html.erb
<header class="header-10">
	<div class="container">
		<div class="navbar col-sm-12" role="navigation">
			<div class="navbar-header nav-dark">
				<button type="button" class="navbar-toggle"></button>
				<a class="brand" href="/">
					<%= render 'layouts/brand_svg' %>
				</a>
			</div>
			<div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
				<ul class="nav pull-left">
					<% if user_signed_in? %>
						<% unless current_user.status == 'merchant' %>
							<li><%= link_to "Become a merchant", become_merchant_path %></li>
						<% end %>
						<li class="dropdown nav-user-options">
							<a href="#" class="dropdown-toggle usernavprofile dropdownselectactive"  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								<% if current_user.profile.present? && current_user.profile.first_name.present? %>
									<%= current_user.profile.first_name %>
								<% else %>
									<%= current_user.email %>
								<% end %>
								<% if current_user.get_avatar_url.present? %>
									<img src="<%= current_user.get_avatar_url %>" width="40" height = "40" class="img-circle profile-nav"/>
								<% else %>
									<img src="<%= asset_url('default-avatar.png') %>" width="40" height = "40" class="img-circle profile-nav"/>
								<% end %>
							</a>
							<ul class="dropdown-menu profile-nav-dropdown">
								<li><%= link_to 'Edit Profile', profile_path  %></li>
								<li><a href="/users/invitation/new">Invite Friends</a></li>
								<% if current_user.status == 'merchant' %>
									<li><%= link_to 'Account Settings', accounts_path %></li>
								<% end %>
								<li><a rel="nofollow" data-method="delete" href="/users/sign_out">Log Out</a></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Become a merchant", become_merchant_path %></li>
						<li><%= link_to "Login", new_user_session_path() %></li>
						<li><%= link_to "Sign Up", new_user_registration_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_result_header_backup.html.erb
<header class="header-10">
	<div class="container">
		<div class="navbar col-sm-12" role="navigation">
			<div class="navbar-header nav-dark">
				<button type="button" class="navbar-toggle"></button>
				<a class="brand" href="/">
					<%= render 'layouts/brand_svg' %>
				</a>
			</div>
			<div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
				<% if @is_search %>
					<form class="navbar-form navbar-right navsearch-form" id="result-filter" method="POST" action="/products/result">
						<%= tag(:input, :name => 'authenticity_token', :type => "hidden", :value => form_authenticity_token) %>
						<% ProductCategory.order('id').each do |category| %>
							<input type="hidden" name="category_<%= category.id %>" value="<%= "1" if @categories["category_#{category.id}"].present? && @categories["category_#{category.id}"].to_i %>">
						<% end %>

						<div class="form-group">
							<input type="text" class="form-control navsearch" style="width: 440px;" id="search-location" name="city" placeholder="Search" value="<%= @city %>">
						</div>
					</form>
				<% end %>
				<ul class="nav pull-left">
					<% if user_signed_in? %>
						<% unless current_user.status == 'merchant' %>
							<li><%= link_to "Become a merchant", become_merchant_path %></li>
						<% end %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle dropdownselectactive" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								<% if current_user.profile.present? && current_user.profile.first_name.present? %>
									<%= current_user.profile.first_name %>
								<% else %>
									<%= current_user.email %>
								<% end %>
								<% if current_user.get_avatar_url.present? %>
									<img src="<%= current_user.get_avatar_url %>" width="28" height = "28" class="img-circle profile-nav"/>
								<% else %>
									<img src="<%= asset_url('default-avatar.png') %>" width="40" height = "40" class="img-circle profile-nav"/>
								<% end %>
								<!-- <img src="https://s3.amazonaws.com/uifaces/faces/twitter/jeanniehuang/128.jpg" width="40" class="img-circle profile-nav"/> -->
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to 'Edit Profile', profile_path  %></li>
								<li><a href="#">Invite Friends</a></li>
								<% if current_user.status == 'merchant' %>
									<li><%= link_to 'Account Settings', accounts_path %></li>
								<% end %>
								<li><a rel="nofollow" data-method="delete" href="/users/sign_out">Log Out</a></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Become a merchant", become_merchant_path %></li>
						<li><%= link_to "Login", new_user_session_path() %></li>
						<li><%= link_to "Sign Up", new_user_registration_path %></li>
					<% end %>

				</ul>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_white_header.html.erb
<nav class="navbar navbar-white  navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<button data-toggle="collapse-side" 
				data-target=".side-collapse" 
				data-target-2=".side-collapse-container" 
				type="button" 
				class="navbar-toggle pull-left">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>

			<a class="navbar-brand" href="/"><img src="<%= asset_url('dummylogo.png') %>" width="30"></a>
			<% if @is_search %>
				<form class="form-inline search-white-nav" id="result-filter" method="POST" action="/products/result">
					<%= tag(:input, :name => 'authenticity_token', :type => "hidden", :value => form_authenticity_token) %>
					<% ProductCategory.order('id').each do |category| %>
						<input type="hidden" name="category_<%= category.id %>" value="<%= "1" if @categories["category_#{category.id}"].present? && @categories["category_#{category.id}"].to_i %>">
					<% end %>
				  <div class="form-group">
						<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
				  </div>
				  <div class="form-group">
						<input type="text" class="form-control search-nav" id="search-location" name="city" placeholder="Search" value="<%= @city %>">
				  </div>
				</form>
			<% end %>
		</div>
		<div id="navbar" class="navbar-collapse   side-collapse in">
			<nav role="navigation" class="navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<% unless current_user.status == 'merchant' %>
							<li><%= link_to "Become a merchant", become_merchant_path %></li>
						<% end %>
						<li class="dropdown">
							<a href="#"  onmouseover="javascript:stickDropdown(this);" class="dropdown-toggle usernavprofile"  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								<% if current_user.profile.present? && current_user.profile.first_name.present? %>
									<%= current_user.profile.first_name %>
								<% else %>
									<%= current_user.email %>
								<% end %>
								<% if current_user.get_avatar_url.present? %>
									<img src="<%= current_user.get_avatar_url %>" width="30" height = "30" class="img-circle profile-nav"/>
								<% else %>
									<img src="<%= asset_url('default-avatar.png') %>" width="30" height = "30" class="img-circle profile-nav"/>
								<% end %>
								<!-- <img src="https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg" width="30" class="img-circle profile-nav"/> -->
							</a>
							<ul class="dropdown-menu profile-nav-dropdown">
								<li><%= link_to 'Edit Profile', profile_path  %></li>
								<li><a href="/users/invitation/new">Travel Credit</a></li>
								<li><%= link_to 'Store Settings', accounts_path %></li>
								<li><a rel="nofollow" data-method="delete" href="/users/sign_out">Log Out</a></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Become a merchant", become_merchant_path %></li>
						<li><%= link_to "Login", new_user_session_path() %></li>
						<li><%= link_to "Sign Up", new_user_registration_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
		<!--/.nav-collapse -->
	</div>
</nav>

app/views/layouts/_white_header_fixed.html.erb
<nav class="navbar navbar-white-fixed  navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button data-toggle="collapse-side" 
				data-target=".side-collapse" 
				data-target-2=".side-collapse-container" 
				type="button" 
				class="navbar-toggle pull-left">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>

			<a class="navbar-brand" href="/"><img src="<%= asset_url('dummylogo.png') %>" width="30"></a>
			<% if @is_search %>
				<form class="form-inline search-white-nav" id="result-filter" method="POST" action="/products/result">
					<%= tag(:input, :name => 'authenticity_token', :type => "hidden", :value => form_authenticity_token) %>
					<% ProductCategory.order('id').each do |category| %>
						<input type="hidden" name="category_<%= category.id %>" value="<%= "1" if @categories["category_#{category.id}"].present? && @categories["category_#{category.id}"].to_i %>">
					<% end %>
				  <div class="form-group">
					<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
				  </div>
				  <div class="form-group">
						<input type="text" class="form-control search-nav" id="search-location" name="city" placeholder="Search" value="<%= @city %>">
				  </div>
				</form>
			<% end %>
		</div>
		<div id="navbar" class="navbar-collapse   side-collapse in">
			<nav role="navigation" class="navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<% unless current_user.status == 'merchant' %>
							<li><%= link_to "Become a merchant", become_merchant_path %></li>
						<% end %>
						<li class="dropdown">
							<a href="#"  onmouseover="javascript:stickDropdown(this);" class="dropdown-toggle usernavprofile"  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								<% if current_user.profile.present? && current_user.profile.first_name.present? %>
									<%= current_user.profile.first_name %>
								<% else %>
									<%= current_user.email %>
								<% end %>
								<% if current_user.get_avatar_url.present? %>
									<img src="<%= current_user.get_avatar_url %>" width="30" height = "30" class="img-circle profile-nav"/>
								<% else %>
									<img src="<%= asset_url('default-avatar.png') %>" width="30" height = "30" class="img-circle profile-nav"/>
								<% end %>
								<!-- <img src="https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg" width="30" class="img-circle profile-nav"/> -->
							</a>
							<ul class="dropdown-menu profile-nav-dropdown">
								<li><%= link_to 'Edit Profile', profile_path  %></li>
								<li><a href="/users/invitation/new">Travel Credit</a></li>
								<li><%= link_to 'Store Settings', accounts_path %></li>
								<li><a rel="nofollow" data-method="delete" href="/users/sign_out">Log Out</a></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Become a merchant", become_merchant_path %></li>
						<li><%= link_to "Login", new_user_session_path() %></li>
						<li><%= link_to "Sign Up", new_user_registration_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
		<!--/.nav-collapse -->
	</div>
</nav>

app/views/layouts/product_detail_backup.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <% if content_for?(:head) %>
    <%= yield(:head) %>
  <% end %>

  <%= favicon_link_tag 'favicon.ico' %>
  <title><%= page_title yield(:page_title) %></title>
  <%= stylesheet_link_tag    'application_detail', media: 'all' %>
  <%= javascript_include_tag 'application_detail' %>
  <%= csrf_meta_tags %>
  <%= Gon::Base.render_data %>
</head>
<body>

  <%= render 'layouts/result_header' %>
  <%= render 'shared/flash' %>
  <%= yield %>
  <%= render 'layouts/footer' %>

  <style type="text/css">
    
  </style>
</body>
</html>

app/views/layouts/product_result.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">


  <% if content_for?(:city) %>
    <%= yield(:city) %>
  <% end %>

	<!-- og meta for facebook share -->
	<meta property="fb:app_id" content="myid" /> 
  <meta property="og:type"   content="sdff:post" /> 
  <meta property="og:url"    content="testtest" /> 
  <meta property="og:title"  content="Sample" /> 
  <!-- <meta property="og:image"  content="https://fbstatic-a.akamaihd.net/images/devsite/attachment_blank.png" /> -->


	<%= favicon_link_tag 'favicon.ico' %>
  <title><%= page_title yield(:page_title) %></title>
  <%= stylesheet_link_tag    'application_result', media: 'all' %>
  <%= javascript_include_tag 'application_result' %>
  <%= csrf_meta_tags %>
  <%= Gon::Base.render_data %>
</head>
<body>

	<div class="page-wrapper">
    <%= render 'layouts/header' %>
    <%= render 'shared/flash' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
	

	<style type="text/css">
		.header-10 .navbar .brand {
      margin-top: -9px;
      padding-top: 0;
    }
    .navbar {
      padding-top: 0;
    }
	</style>
</body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<% if content_for?(:meta) %>
    <%= yield(:meta) %>
  <% end %>
	
	<%= favicon_link_tag 'favicon.ico' %>
  <title><%= page_title yield(:page_title) %></title>
  <%= stylesheet_link_tag    'application_static', media: 'all' %>
  <%= javascript_include_tag 'application_static' %>
  <%= csrf_meta_tags %>
  <%= Gon::Base.render_data %>

</head>
<body>

	

	<div class="page-wrapper">
		<%= render 'layouts/header' %>
		<!-- Second navbar -->
		<%= render 'shared/static_nav', :obj => @nav_obj %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
	
	<style type="text/css">
		
	.h4-behave {
		font-size: 32px;
	}
	.panel {
    border: 1px solid #dce0e0;
    background-color: #fff;
    -webkit-border-radius: 0;
    -moz-border-radius: 0;
    border-radius: 0;
}
.panel-body {
    position: relative;
    margin: 0;
    padding: 20px;
   
}
.row-space-4 {
    margin-bottom: 25px;
}
	.col-6 {
    width: 50%;
    float: left;
}
.press-content a {
    color: #565a5c;
}
small {
    font-size: 0.85em;
}
	</style>
</body>
</html>